# Naive Bayes Practical Implementation

![](https://i.imgur.com/CLYHQ8e.jpg)

In [4]:
import pandas as pd
import numpy as np

In [2]:
from sklearn import datasets
wine = datasets.load_wine()

In [3]:
print(wine)

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 


### <font color = green>Extract features from the above wine array</font>

In [4]:
print(wine.feature_names)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [6]:
print(wine.target_names)

['class_0' 'class_1' 'class_2']


In [7]:
X = pd.DataFrame(wine['data'])
X.head()

0     1     2     3      4     5     6     7     8     9     10    11  \
0  14.23  1.71  2.43  15.6  127.0  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100.0  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101.0  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113.0  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118.0  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

       12  
0  1065.0  
1  1050.0  
2  1185.0  
3  1480.0  
4   735.0

In [8]:
y = (wine['target'])
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y, test_size=0.30,random_state=100)

In [10]:
x_train.shape,y_train.shape

((124, 13), (124,))

### Import GaussianNB

In [15]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train,y_train)
y_pred = gnb.predict(x_test)
print(y_pred)

[1 2 0 1 2 2 1 1 1 1 2 1 2 2 2 0 2 0 1 0 2 0 1 1 0 0 1 1 1 2 2 1 0 1 2 2 1
 1 2 2 0 2 2 2 0 2 2 2 0 0 0 1 0 1]


In [27]:
from sklearn import metrics 
metrics.accuracy_score(y_test,y_pred)

0.8743718592964824

In [18]:
from sklearn.metrics import confusion_matrix
cm = np.array(confusion_matrix(y_test,y_pred))

cm

array([[14,  0,  0],
       [ 0, 19,  0],
       [ 0,  0, 21]], dtype=int64)

- Here we can see our model has predicted all correct values, because in confusion matrix all diagonal values are correct values and any values other then diagonal values are incorrect. Like in our case all non-diagonal values are zero ..<br><br>
Another Example <br>
![](https://i.imgur.com/B7nMweI.png)<br>
Here in this example the model has predicted 5 wrong values. Because the diagonal values are for correct assumptons and values other then diagonal are wrong values<br>
In this example 2+2+1 = 5, So 5 are wrong prediction and rest are current predictions

## <font color=violet>Naive Bayes' Classification on text data</font>
### <font color = green>Spam-Classification</font>

In [5]:
Dataset = "https://raw.githubusercontent.com/sunnysavita10/Naive-Bayes/main/SpamClassifier-with-ML/sms_spam_data/SMSSpamCollection.csv"

In [6]:
data = pd.read_csv(Dataset,sep="\t",header = None,names=['label',"messages"])
data

label                                           messages
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [7]:
data['messages'][0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [8]:
# NLTK: Natural Language Toolkit
import nltk
import re  

Regular Expression`re:` it is used for finding out pattern in our text dataset   

In [9]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to C:\Users\SAHIL
[nltk_data]     JOSAN\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

`Stop words` are a set of commonly used words in a language. Examples of stop words in English are `“a”`, `“the”`, `“is”`, `“are”` and etc. Stop words are commonly used in Text Mining and Natural Language Processing (NLP) to eliminate words that are so commonly used that they carry very little useful information.

In [10]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [11]:
# For stemming
ps = PorterStemmer()

In [12]:
data['messages'][0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

Clean the data and then do vectorization <br>
Cleaning the data includes
- removing "a","e" or any this type of single character
- make all character in the dataset `lower`
- do stemming of the data
<br><br>
![](https://d2mk45aasx86xg.cloudfront.net/difference_between_Stemming_and_lemmatization_8_11zon_452539721d.webp)
<br><br>
Lemitization takes more time compare to stemming

In [13]:
corpus = []
for i in range(0,len(data)):
    review = re.sub('[^a-z,A-Z]',' ',data['messages'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)
    

Now we have appended everything into our corpus

In [14]:
len(corpus)

5572

In [15]:
corpus[:20]

['go jurong point, crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf, live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send, rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight, k cri enough today',
 'six chanc win cash , pound txt csh send cost p day, days, tsandc appli repli hl info',
 'urgent week free membership , prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word tha


### <font color=green>Convert this data into vector</font>
We go in sklearn.feature_extraction <br>
Here we can use any vectoriser to convert our data into vector

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
cv = CountVectorizer()

In [18]:
X = cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

Now our data is converted into vectors

In [19]:
X.shape
# 5572 rows 
# 6531 columns

(5572, 6531)

WE CAN REDUCE THE NUMBER OF FEATURES BY USING max_features PARAMETER

In [20]:
cv = CountVectorizer(max_features = 2500)
X1 = cv.fit_transform(corpus).toarray()
X1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
X1.shape

(5572, 2500)

Our target column is:

In [22]:
data['label']

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: label, Length: 5572, dtype: object

In [23]:
pd.get_dummies(data['label'])

ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5572 rows x 2 columns]

Code To get only spam feature 

In [24]:
y = pd.get_dummies(data['label'], drop_first=True)
y

spam
0        0
1        0
2        1
3        0
4        0
...    ...
5567     1
5568     0
5569     0
5570     0
5571     0

[5572 rows x 1 columns]

### <font color=green>Train Test Split</font>


In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=10)

In [29]:
# Model training
from sklearn.naive_bayes import GaussianNB
model  = GaussianNB()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
print(y_pred)

c:\Users\SAHIL JOSAN\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0 0 0 ... 0 0 1]


In [33]:
# Check Accuracy
from sklearn import metrics 
print("Accuracy by GaussianNB: ",metrics.accuracy_score(y_test,y_pred))

Accuracy by GaussianNB:  0.8743718592964824


### <font color=green>Check accuracy with multinomialNB</font>

In [32]:
from sklearn.naive_bayes import MultinomialNB
model2 = MultinomialNB()
model2.fit(x_train,y_train)
y_pred2 = model2.predict(x_test)
print("Accuracy Score by MulinomialNB: ",metrics.accuracy_score(y_test,y_pred2))

c:\Users\SAHIL JOSAN\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy Score by MulinomialNB:  0.9691313711414213
